shell = "zsh"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
dir = "src"
apply = ["fpath"]
profiles = ["completion"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
profiles = ["interactive"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
profiles = ["interactive"]
