{
	"data": "ENC[AES256_GCM,data:FKYxBDKZB4ou5r9FHz5rTK80G9bbWqooeTCyW1xf/CWsMDWbDw8PDqPdEQgX2eQr6tC18wooHpRHq3VIs/0PFyQNhwFTBgP4MR1jkr5tQxKaEoj59As/17zDqmfX8VhO96/PIw1kXD3zcVyEvKXeW09fru0rKjgNlQyFV5Zf5JMexGXdyc/VWHe65oduHyFIIi5wQ7Rc3+Z9I9RAgcwO2NyMFxeB5zKU8J56P6TWiwyNQulsTT6pAg/aPrd3IxmWd1ObzCYoVf/EelpXpZA6/DA8lLc3IhNRGsAgtzl1XE3AObx7mv5b9VyYQV1s7GJ9MgLHe3rwCxRjBxUXbmvXhxwuyGF4d3SdkqciZaUoOz4bDCHyocE9JK4loHAIlfnSDYWOtZnw1JePYlmjmvvwC9CQq4WeuwP55mnO1af/lD1rd2kYkYOWv52fcwLksx71XUbWZOXaO6rd2iJxbVUvTlJOAKcKaElJlYWONYRUDJ1rfRBRqCJCcuMPrQ9scmU54euhj3qRIICOzP6M0wLdAq9PpgiiS2Vzy9fds+DIfiLSCDcVGdL4hng0esoeAVKF60FUsgAaHU9r+7GLsWElOvwHdoNd+Whd/clo4wiEeZL+wSi3sLXOaQ91GkdBDGlyxIGl7aLhgsHVjXw7oM8MngLF3FqxURrLhhPmi26K12z19CKIYyD9GDftmrfryVE/UwbOVcq6ut3xuyVfhhfkAFKh6nCvPo/nLLnDZQsF1q1gbfLo44TNkTStSRo5m0O3jztudviWJAHIu7n/l/+PPbkkXFkej7LwKSCiiCgODKITE0QwymUdCYa6TyX7Dyos5aRQYfS1zhudUXYS9qNQ5uvIu8e2,iv:ggTGvMy7SR1jCxwNtNen3BL6X8OTLTMc2mKQyGzidcE=,tag:5FIE3Yntv4p1ptaVvGHDMA==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVFFyUXBVSHkvU0R1TTNw\nQUQxejBFaENnMmZVa3lKRzN0T0pnVmMrUGdZCm9jeGp5RXRhSEY0R2ZNNFRCTk11\ndFVYQlhrSzhCK0hvSFpFVzRvTmpKYTgKLS0tIFg0MjAwVzVsTm9mSnI4YXBhZS9S\nRFgwWXozanExcjFML0RhS1M3eis3eUEKf+329Air0QETVB65ArEnPOezs5rjsTAi\nGZQj3vC0DcjWw8KdSmmU24wCPxE6H4IrWye9rrgetoJGE7W6MQhxOg==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1w8w47te4h3ppmjjmlpmkzvm7pxlwyzrd3cwuhvv0cw9hxw8qja8qaql7mf"
			}
		],
		"lastmodified": "2026-07-18T14:47:27Z",
		"mac": "ENC[AES256_GCM,data:EDXHMt2M9VFYn0Mk00VBwR6UitqsMqdIK9NNgLOSctehkyjdCpXJfKng6fyEe4FnXlwBWFX/roCi0ZUoPiow4ljwfKQXBCrpYWy+PvZYGeNL/UnkxzZtzFs6ywqRfLPfq3f1rKf0K5XfsV1nNmmNeDbJefj+QNVQErJUdXo8UPc=,iv:sbnG7oCu3+SIwUxwp0Fqk55vofOKzOeg9xkt7aCGozc=,tag:l+IKYWdZeqT++4+rj6xc8w==,type:str]",
		"pgp": [
			{
				"created_at": "2026-07-18T14:47:27Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhF4DGLUi+eg7dfYSAQdA3PBYvtM9+iHcNF0i2/D+sCRdg3yHwrmgoaNSbP2M2igw\nrFQ3tHJhEfgQYufGZrfg4JOMoKcpZyELvmJy6GIoUDDfLMl0f7SoVA4RMNHsKLj6\n0l4BofRrl8V4UrEv7mzFQMO7k7+8p80Gamklj0UVckhES6XXtTfbIUb1a+XdoSNu\nFAODrP8wzXbRc+xy+Ps5Nj9gI794DJM+Bf2ROJxh/Gpsqt1ZQg6Xyl1+hr+1hGqg\n=BVIU\n-----END PGP MESSAGE-----",
				"fp": "11D7A68D97E0C636DF487CA1C55CCC13D8D16739"
			}
		],
		"version": "3.13.2"
	}
}
