{
	"data": "ENC[AES256_GCM,data:qnyWFcOa6vyayfaElbV+3CCp14K6X349m1HmTLo1CKsnhFWLAYlk5Ikwl9gAc5KUopC3fhXdTh38KwoU0FwubxrQGpKuiReYnLan6tP4TkaEVia6ikb7ZBAzH6jRyDCSeYZytg5xnlHGXnSvZ9gFhIdR/Bg519rP2egtlpZk1wLsTM09a49NfVjrfMD+ziOytfAcqqfxD95Bb+e2TR0VN9OmVNl/Z5clARL52IMrZTA300PKIGx81DSdWKaGTP/HVxwNQfly628bf8thLtuhJ1xBNYBk6dcTBISr+LXHklvg0zkDA1Q3XnMZMXdL7ypc98iUBGGfTXjYglqLW/HY7Mavv4XGo1y9VVmYTGwPI1nRrOoA/xhjcUPTYQhXx7pjf0E4GHGFTd5PDb2N7e19/xz41BVpKT7rHo81nvDg36IcmLs259GjpAjnORAFD6/OJQgDExPYCkVxer9EO4C5JNPIyIHdXIJGET7FcpigWfmibkr+UFxARSffYZSL42V2HQWjM9+V09qtPWPQSX4BwtlYocIHyRal65/aa4iVVKlufZDuptqwbkKwU0N0z4gnBgxIgp6Im6DVHyPZ+31FLKzEs9+A0IwHxOfT2wH90iDcZauWn1UZRTYptwE1WxJWpe2pliN7+k/zKnCNkkBFzzG9mGHN/4sunTTK/8aLBRLOa49WPeU/j5jW62D6up0+zzNdLS6OK3UP7nDLoKqXFMP8pdaOS9qRciBMfij9xjU0Pdh8Zne+pGaftKqSyuo9fz4xw7PeXMjTuJCZzERfqdBIV2383oBOLvxEPDNl2QL1kpnT8FUpWMt7TgdrEGgDjcSELWgVnOHbMCqs7jOOd9wdZxK1,iv:2B46stXRheU2Q944BXW1RnLyJuKUEdqxFmDzRzJpRNs=,tag:rXwl96Ku+C5zFWpqt1643A==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsczZMeVlQYVlVclo3di9D\nd0l6Q3ByNm51aGNWTHRubWJPYVVSTW52OVhzClBKeVRJL2RRd2FpKzg3VlJBdGh0\nQmtxVDZ5cjdpdUJJRnoyMWwzR0JDWWcKLS0tIFhhM29TZS80bkJiVS9KcXpHR3lt\nUUlWOFBFOStlME1XT3hxZytJN2JNM2MKm1fo3ZigLw2+UqXwKb9xHL76ZieyozlG\nNEDieDVJj9G06grP5GOXZjX3p620Fs9PUImlF0JG1tcg+8ou9yAeGg==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1w8w47te4h3ppmjjmlpmkzvm7pxlwyzrd3cwuhvv0cw9hxw8qja8qaql7mf"
			}
		],
		"lastmodified": "2026-06-25T08:38:37Z",
		"mac": "ENC[AES256_GCM,data:9gbYdqXYfdUeRuFi2xlfbIwgh+AFKPxWfBUn3bcJ+DqkOxGm6MPTFoacIrdQeDTqDSP7YdSsKV5Lz732BlOMs7duKOvD2l5VlmyJQL3MmjjIX/H6bDB9iQ88EdDQmqtrxRmHcc1jvVs1/I+NDlPUgde52NyCn73E3A9O5k3twOY=,iv:jEbO5KL3l4UyR9kCQCUP+aQnkvyIeAx6uOkZnDUacas=,tag:g+U4r+NEPbkKxkejio2xEw==,type:str]",
		"pgp": [
			{
				"created_at": "2026-06-25T08:38:37Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhF4DGLUi+eg7dfYSAQdAKhkQ4MSVQ+0ZOcjhGiYvSfdgwHe3G7V8IKRUj4Kh0gMw\najr3xgFOMnGCBOJ1fR1XzdJH9DXldlHWVU8SKtwbmlkc3rS96Ns/xRvEsvP1hY86\n0lwB1yVlGGMWb2nxVWOG1M6yE9YZhGOto+7wSOVW5aCL/Ve+lewwzJBoZV9RHwsK\nMfNUDxDZl4+pHYQP5dLjp3v8JLV8dqeyTbdNCnnBbLSI2VXuMilk841gm3zIhg==\n=W/d3\n-----END PGP MESSAGE-----",
				"fp": "11D7A68D97E0C636DF487CA1C55CCC13D8D16739"
			}
		],
		"version": "3.13.1"
	}
}
