{
	"data": "ENC[AES256_GCM,data:xSSdvhp/2R/fEJLLnh+caGGpftN+qTDhyulHrpUR/LDc1smEoaQegYpFvXUj7FjlU9TGZjwW+C5eCirWCLBl3cmly7JelmFtedDa2ItsOxUgV8kDiZR7xd+qy8oQ7f2W9ZyTfFjcP223u+TRYn2Np5GdSipadG95NwPffGpAJQge9/bgcRTkTR/jfgl4lE7ZJ3Cp6dgoPC+Qz/umg4G6lUQDsr3AicNYjtmI+FVRo8DwlNYJx9QGw7JanJ8vGjzBiL932z05UxNm9tFqThC665LtJsoVD4oX2nnOqVUEnNswDJRNqnxDIuYaVtS2wcwlS+NUN+NLPaDVsd4wLO3TVv5pB1xI6vncc46wOdktR2Oc23kR+t3vjpJznC24SIfSt/aNDpaVmjOoKsr1vinHuLs+z5sGGrzpmVV6JLVzjwYS49YI0ajTEd1MTP1zpS3ueotVdlKMiPX3Dr5FbqjeHImUuxTGLf2gPxTHs0UrLKQ/hNcUzKx8hPRFHH9tqkzbC5mq3Eb5w4LPFS7lXrQZnt5X4PogvEv6SvVVujZCsTThC97krLbleQ9/2O1BZBPA29mPBwrTuaR/HfbbJSRz9MjYcbRXip4v0fG8NLoBYNZiVSF/Eit3uJZ16UEm01P4+ycF2K40wvPYp5UNFWMa8pSIDVDXqETPUuDsU0QDxj39RDX+1vdyk0j7AjuQxW9s5KxuZzkyc9kCVphpXYnTFhJ/EOihno4pY+KDACzIgmFvvLU2hGud/rrxphFcX3DnKjUTmCqT/zZWkmHeuBG+Y/Um5Pf9PH87XzEYBec80frzr6IzFW3ru0gp1qx1oNWMvjxHGaAyiu94CwxALnNqHTxwm0VdMv0Dw9IuWx0=,iv:Qp39X/Fcj/SGwShexuKXeNwUb8KegU6qa2Zrkjm0EGI=,tag:y6LvAdZyuzaRz9V9QQtypw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUFI1Ryt2ZFJvY0EzckE3\nbUYzRTN0cWhDNGhoM1pQcm9ac0VnT3ZKUWxVCmtRNGFGSjVTcGVyNjZ1US8vNk9Y\nN2locmxTc1dpTndwWW9HRVpvc3FKUzQKLS0tIDkxK0RqY2xTb0hCYmhnUTBBa2FX\nVzJrTWd6eEgyVWtYQms0b2JWVFJsMU0Kups1cCy+xMHAoDoG9LVfQl7J3urvPpDb\nu5mWescn7CJQLaeIUiEC0v+sMinKjIe4Hm+BeEOZo/iLLkHyo7R5OQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1w8w47te4h3ppmjjmlpmkzvm7pxlwyzrd3cwuhvv0cw9hxw8qja8qaql7mf"
			}
		],
		"lastmodified": "2026-08-12T17:01:44Z",
		"mac": "ENC[AES256_GCM,data:DsJksJb6GjN+F7E4EIblYkYlMryAfIhxt9oeINL1pabo+Wcvbe/qtPSTw+6wbKG1FrakFSuLLM7Aw5JYkbGAkwoiYsr93svWjkL3j+SJI1R880Q/InExP8nYuClIEm/YV03pnn8ZRoPDe9W7CPVZ9roTqT9JsqllT8KCv9nHQNo=,iv:jOboH7aZXpfvgQRkmF+SOZ9PY00cIapLobuFXRormSs=,tag:vCteA9obglvOPpu3VGHsbA==,type:str]",
		"pgp": [
			{
				"created_at": "2026-08-12T17:01:44Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhF4DGLUi+eg7dfYSAQdAHnWik00sVnsdOE0InaHc5sO2mDkd38R7AnIXPT/lTBIw\nHw9KwrgwX5K13aFlF7zH91iTbk60OB1pM11Pi3aA2CaEgor+2EjRnOizoG14U0sW\n0l4BqVEARC+w2ziCeGFQah+FCpH34+YLJTzrwvSKR+Xb1kTiFTURQO2CL/dJYiB2\nZnfQv0lg2E+gmOWuXYI/JvBi0Q/yL8i+x0fBcuNoH6WvB6O4liaotcXUWRlMjseY\n=w/fZ\n-----END PGP MESSAGE-----",
				"fp": "11D7A68D97E0C636DF487CA1C55CCC13D8D16739"
			}
		],
		"version": "3.13.3"
	}
}
