{
  pkgs,
  config,
  # vscode-server,
  ...
}:

{
  imports = [
    ./hardware-configuration.nix
    ./nfs.nix
    # ./jellyfin.nix
    # ./ldap.nix
    # vscode-server.nixosModules.default
  ];

  networking.hostName = "NixOS-sandi-lenovo";
  networking.hostId = "938fc0bf"; # for zfs. generated by `head -c 8 /etc/machine-id`

  environment.systemPackages = with pkgs; [
    # deploy-rs
    # colmena
    # ragenix.packages.${system}.default
    gptfdisk
    zfs
    libarchive # for bsdtar
  ];

  services.openssh = {
    extraConfig = ''
      AllowAgentForwarding yes
      StreamLocalBindUnlink yes
    '';
  };

  /*
    services.vscode-server = {
      enable = true;
    };
  */

  /*
    nixpkgs.config.allowUnfree = true;
    services.plex = {
      enable = true;
      openFirewall = true;
      dataDir = "/nfs/plex";
    };
  */
  services.nextcloud = {
    enable = true;
    hostName = "localhost";
    config.dbtype = "sqlite";
    config.adminpassFile = config.age.secrets."mackerel_apikey".path;
  };
  system.stateVersion = "24.11";
}
