{
  config,
  pkgs,
  # vscode-server,
  ...
}:

{
  imports = [
    ./hardware-configuration.nix
    # ./nfs.nix
    ../pkgs/portunus
    ../pkgs/ldap
    ../pkgs/netdata
    ../pkgs/vaultwarden
    ./nextcloud.nix
    # ./gotify.nix
    ./scrutiny.nix

    ./prometheus.nix
    ./yace.nix
    ./myserv
  ];

  networking.hostName = "NixOS-sandi-lenovo";
  # networking.hostId = "938fc0bf"; # for zfs. generated by `head -c 8 /etc/machine-id`

  environment.systemPackages = with pkgs; [
    gptfdisk
    libarchive # for bsdtar
  ];

  # [START] sssd
  sops.secrets.sssd-env = {
    format = "binary";
    sopsFile = ./secrets/sssd-env.enc;
    mode = "0400";
  };
  services.sssd = {
    enable = true;
    sshAuthorizedKeysIntegration = true;
    environmentFile = config.sops.secrets.sssd-env.path;
    settings = {
      sssd = {
        config_file_version = 2;
        services = "nss, pam, ssh";
        domains = "portunus";
      };
      "domain/portunus" = {
        auth_provider = "ldap";
        id_provider = "ldap";
        ldap_uri = "ldap://localhost:389";
        ldap_search_base = "dc=sandi05,dc=com";
        ldap_default_bind_dn = "uid=techadmin,ou=users,dc=sandi05,dc=com";
        ldap_default_authtok_type = "password";
        ldap_default_authtok = "$SSSD_LDAP_DEFAULT_AUTHTOK";
        ldap_id_use_start_tls = false;
      };
    };
  };
  # [END] sssd

  system.stateVersion = "25.11";
}
