{
  pkgs,
  # vscode-server,
  ...
}:

{
  imports = [
    ./hardware-configuration.nix
    ./nfs.nix
    ./jellyfin.nix
    ./portunus.nix
    ./keylytix.nix
    # ./ldap.nix
    # vscode-server.nixosModules.default
  ];

  networking.hostName = "NixOS-sandi-lenovo";
  networking.hostId = "938fc0bf"; # for zfs. generated by `head -c 8 /etc/machine-id`

  environment.systemPackages = with pkgs; [
    # ragenix.packages.${system}.default
    gptfdisk
    zfs
    libarchive # for bsdtar
  ];

  /*
    services.vscode-server = {
      enable = true;
    };
  */

  system.stateVersion = "24.11";
}
