shell = "zsh"

# 補完定義の追加
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
dir = "src"
apply = ["fpath"]
profiles = ["completion"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
profiles = ["interactive"]
