# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        rocmPackages.clr.icd
      ];
    };
  };
  boot = {
    kernelModules = [
      "amdgpu"
      "kvm-amd"
      "v4l2loopback"
    ];
    extraModulePackages = with config.boot.kernelPackages; [
      v4l2loopback
    ];
    extraModprobeConfig = ''
      options v4l2loopback devices=1 video_nr=1 card_label="OBS Cam" exclusive_caps=1
    '';

    # supportedFilesystems.btrfs = true;

    initrd = {
      availableKernelModules = [
        "dm-crypt"
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "thunderbolt"
      ];
      kernelModules = [
        "dm-snapshot"
        "vfat"
        "nls_cp437"
        "nls_iso8859-1"
        "usbhid"
      ];

      services.lvm.enable = true;
      luks = {
        cryptoModules = [
          "aes"
          "xts"
          "sha512"
        ];
        yubikeySupport = true;

        devices."root" = {
          device = "/dev/disk/by-uuid/fc9ffc33-fe2b-4cc5-a334-8abd73882e04";
          preLVM = false;
          yubikey = {
            slot = 1;
            twoFactor = true;
            gracePeriod = 30;
            keyLength = 64;
            saltLength = 32;
            storage = {
              device = "/dev/disk/by-uuid/12CE-A600";
              fsType = "vfat";
              path = "/crypt-storage/default";
            };
          };
        };
      };
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4f1f0d84-1d4a-4c0c-a83a-8a331a57f719";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  /*
    environment.etc."crypttab" = {
      mode = "0600";
      text = ''
        swap /dev/mapper/nixos-swap /dev/urandom swap,cipher=aes-xts-plain64,size=256
      '';
    };
  */

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/a01365ba-b6e0-4e68-ad04-adba224ea5c0";
    }
  ];

  /*
    services.btrfs.autoScrub = {
      enable = true;
      fileSystems = [ "/" ];
    };
  */

  services.xserver = {
    enable = true;
    videoDrivers = [ "amdgpu" ];
  };
  environment.systemPackages = with pkgs; [
    rocmPackages.rocminfo
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
