# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        rocmPackages.clr.icd
      ];
    };
  };
  boot = {
    kernelModules = [
      "kvm-amd"
      "v4l2loopback"
    ];
    extraModulePackages = with config.boot.kernelPackages; [
      v4l2loopback
    ];
    extraModprobeConfig = ''
      options v4l2loopback devices=1 video_nr=1 card_label="OBS Cam" exclusive_caps=1
    '';

    supportedFilesystems.btrfs = true;
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [
        "dm-snapshot"
        "vfat"
        "nls_cp437"
        "nls_iso8859-1"
        "usbhid"
        "amdgpu"
      ];

      # services.lvm.enable = true;
      luks = {
        yubikeySupport = true;
        reusePassphrases = false;

        devices."root1" = {
          device = "/dev/disk/by-uuid/20e766b2-579c-497a-bab6-8227f749d031";
          preLVM = false;
          yubikey = {
            slot = 1;
            twoFactor = true;
            gracePeriod = 30;
            keyLength = 64;
            saltLength = 16;
            storage = {
              device = "/dev/disk/by-uuid/12CE-A600";
              fsType = "vfat";
              path = "/crypt-storage/default";
            };
          };
        };

        devices."root2" = {
          device = "/dev/disk/by-uuid/21204e1f-7445-4985-a670-d5143eb762ca";
          preLVM = false;
          yubikey = {
            slot = 1;
            twoFactor = true;
            gracePeriod = 30;
            keyLength = 64;
            saltLength = 16;
            storage = {
              device = "/dev/disk/by-uuid/12CE-A600";
              fsType = "vfat";
              path = "/crypt-storage/default";
            };
          };
        };
      };
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/aefdbaf2-b45a-46f6-a9f6-6c325546f12a";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/aefdbaf2-b45a-46f6-a9f6-6c325546f12a";
    fsType = "btrfs";
    options = [ "subvol=data" ];
  };

  /*
    environment.etc."crypttab" = {
      mode = "0600";
      text = ''
        swap /dev/mapper/nixos-swap /dev/urandom swap,cipher=aes-xts-plain64,size=256
      '';
    };
  */

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/1f8483b5-34f7-4ec3-83bf-69af7d7d1677";
    }
  ];

  services.btrfs.autoScrub = {
    enable = true;
    fileSystems = [ "/" ];
  };

  services.xserver = {
    enable = true;
    videoDrivers = [ "amdgpu" ];
  };
  environment.systemPackages = with pkgs; [
    rocmPackages.rocminfo
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
