add_newline = false
command_timeout = 750
format = "$directory$git_branch$git_status$nodejs$python$character"

[directory]
truncation_length = 3
truncate_to_repo = false
style = "bold cyan"

[git_branch]
symbol = "git:"
style = "bold yellow"

[git_status]
style = "bold red"

[nodejs]
symbol = "node:"
style = "bold green"

[python]
symbol = "py:"
style = "bold blue"

[character]
success_symbol = "[>](bold white)"
error_symbol = "[x](bold red)"
