keys:
    - &yubikey 11D7A68D97E0C636DF487CA1C55CCC13D8D16739
    - &nixos-keishis-p14s age124e8pp8x4g904kyftnt98d68pdsefa68xj73j2jn6800sqwghgaq7wh5u6
    - &nixos-keishis-x13 age1gpnv7cgya70xfz9h0p4ah0wvpl5srq4jktme8v4fwg0m7ljpwyqsh5e5a2
    - &nixos-keishis-home age1x3wren8ffn330kmzclwmle5q5parkwhmljf9hm4uwjcpcygdwy9qzqwlrv
    - &nixos-sandi-lenovo age14w3la5xmucv3glnyt2c26gv37ne5caed2ntuk2gfxrmwlpyfdygs34qm6h
    - &nixos-sandi-n100 age1pn27c7fv0ayma6resthfh955u4zg9ncshrjt3t694zyjqhk79q3qjekg3f
creation_rules:
    - path_regex: ^secrets/.*
      key_groups:
          - pgp:
                - *yubikey
            age:
                - *nixos-keishis-home
                - *nixos-sandi-lenovo
    - path_regex: ^hosts/lenovo/secrets/.*
      key_groups:
          - pgp:
                - *yubikey
            age:
                - *nixos-sandi-lenovo
    - path_regex: ^modules/services/sssd/secrets/.*
      key_groups:
          - pgp:
                - *yubikey
            age:
                - *nixos-sandi-lenovo
    - path_regex: ^modules/services/portunus/secrets/techadmin.enc
      key_groups:
          - pgp:
                - *yubikey
            age:
                - *nixos-keishis-home
                - *nixos-sandi-lenovo
                - *nixos-sandi-n100
    - path_regex: ^hosts/home-srv/.*
      key_groups:
          - pgp:
                - *yubikey
            age:
                - *nixos-keishis-home
    - path_regex: ^hosts/lenovo/myserv/secrets/.*
      key_groups:
          - pgp:
                - *yubikey
            age:
                - *nixos-sandi-lenovo
    - path_regex: ^modules/services/portunus/secrets/.*
      key_groups:
          - pgp:
                - *yubikey
            age:
                - *nixos-sandi-lenovo
    - path_regex: ^modules/services/vaultwarden/secrets/.*
      key_groups:
          - pgp:
                - *yubikey
            age:
                - *nixos-sandi-lenovo
    - path_regex: ^home/keishis/.*
      key_groups:
          - pgp:
                - *yubikey
    - path_regex: .*
      key_groups:
          - pgp:
                - *yubikey
            age:
                - *nixos-keishis-home
                - *nixos-keishis-p14s
                - *nixos-keishis-x13
                - *nixos-sandi-lenovo
                - *nixos-sandi-n100
