{
  pkgs,
  ...
}:

{
  imports = [
    ./hardware-configuration.nix
    ./vaultwarden.nix
    ./nextcloud.nix
    ./jellyfin.nix
    ./nextcloud-media-archive.nix
    ./kanidm.nix
    ./nfs.nix
    ../../modules/services/kanidm-client
  ];

  networking.hostName = "NixOS-sandi-lenovo";
  networking.hostFiles = [ ./hosts.local ];
  # networking.hostId = "938fc0bf"; # for zfs. generated by `head -c 8 /etc/machine-id`

  environment.systemPackages = with pkgs; [
    libarchive # for bsdtar
  ];

  system.stateVersion = "25.11";
}
