{
  pkgs,
  ...
}:

{
  imports = [
    ./hardware-configuration.nix
    ./vaultwarden.nix
    # ./nextcloud.nix
    # ./jellyfin.nix
    # ./nextcloud-media-archive.nix
    # ../../modules/services/kanidm-client
    ../../modules/services/nfs-client
  ];

  networking.hostName = "NixOS-sandi-lenovo";
  # networking.hostId = "938fc0bf"; # for zfs. generated by `head -c 8 /etc/machine-id`

  environment.systemPackages = with pkgs; [
    libarchive # for bsdtar
  ];

  sandi.nfsClient = {
    enable = true;
    mounts = {
      storage = {
        mountPoint = "/storage";
        remote = "calc-serv.sandi05.com:/storage";
      };

      users = {
        mountPoint = "/users";
        remote = "calc-serv.sandi05.com:/users";
      };
    };
  };

  system.stateVersion = "26.05";
}
