{
  pkgs,
  ...
}:

{
  imports = [
    ./hardware-configuration.nix
    ../../modules/services/portunus
    ../../modules/services/ldap
    ../../modules/services/sssd
    ../../modules/services/vaultwarden
    ./nextcloud.nix
    ./jellyfin.nix
    ./nextcloud-media-archive.nix
  ];

  networking.hostName = "NixOS-sandi-lenovo";
  # networking.hostId = "938fc0bf"; # for zfs. generated by `head -c 8 /etc/machine-id`

  environment.systemPackages = with pkgs; [
    gptfdisk
    libarchive # for bsdtar
  ];

  system.stateVersion = "25.11";
}
