# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    kernelModules = [ "kvm-amd" "v4l2loopback" ];
    extraModulePackages = with config.boot.kernelPackages; [
      v4l2loopback
    ];
    extraModprobeConfig = ''
      options v4l2loopback devices=1 video_nr=1 card_label="OBS Cam" exclusive_caps=1
    '';

    initrd = {
      availableKernelModules = [
        "nvme" "xhci_pci" "thunderbolt"
        "usb_storage" "sd_mod"
      ];
      kernelModules = [
        "dm_snapshot" "vfat" "nls_cp437"
        "nls_iso8859-1" "usbhid" "amdgpu"
      ];

      services.lvm.enable = true;
      luks.yubikeySupport = true;
      luks.devices."unlocked" = {
        device = "/dev/disk/by-uuid/9bd1e197-8b0d-41c2-96cc-b890965272a8";
        preLVM = false;
        yubikey = {
          slot = 1;
          twoFactor = true;
          gracePeriod = 30;
          keyLength = 64;
          saltLength = 16;
          storage = {
            device = "/dev/nvme0n1p1";
            fsType = "vfat";
            path = "/crypt-storage/default";
          };
        };
      };
    };
  };

  services.xserver = {
    enable = true;
    videoDrivers = [ "amdgpu" ];
  };
  environment.systemPackages = with pkgs; [
    rocmPackages.rocminfo
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/011fbd36-c7d7-4740-a408-22ab0de8438c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A910-1728";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/d99c9086-e0f1-4c53-8c6e-84fce00ec5cb";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.interfaces.enp51s0f4u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
